import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class Migration_1648906723736_create_platforms_table{
    public static void run() {
        Connection con = Migrate.getConnection();
        try {
            Statement stmt = con.createStatement();
            stmt.execute(
        		"CREATE TABLE platforms (" +
            		"id NUMBER(10, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY (NOCACHE)," +
            		"name VARCHAR2(100) NOT NULL," +
            		"PRIMARY KEY(id)" +
        		")"
    		);
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}